# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: RocSoc.org
author: Lancaster University RocSoc
email: rocsoc@lancaster.ac.uk
description: >- # this means to ignore newlines until "baseurl:"
  We're Lancaster University RocSoc, a society for those who like Rock, Metal or Punk and everything inbetween!
  
#baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rocsoc.org" # the base hostname & protocol for your site, e.g. http://moggrat.com

# Minima date format
minima:
  date_format: "%-d %b, %Y"

  # generate social links in footer
  social_links:
    twitter: rocsoc
    facebook:  lurocsoc
    instagram: lurocsoc
    # youtube_username:
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram_username: jekyll
# social.html stuff

twitter_username: rocsoc
instagram_username: lurocsoc
facebook_username: lurocsoc
#github_username:  moggrat
#youtube_username: moggrat

defaults:
  - scope:
      path: ""
    values:
      image: /assets/logos/logoog.png


# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - about-us.md
 - Gigs.md
 - social.md
 - join-us.md

# - games.md

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-admin
  

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
